// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG2TmElFryA2lfd08zinarCQ-hfmnU_uU',
    appId: '1:178181282925:web:0dc4d94576bf76e784f364',
    messagingSenderId: '178181282925',
    projectId: 'fir-be1fc',
    authDomain: 'fir-be1fc.firebaseapp.com',
    storageBucket: 'fir-be1fc.appspot.com',
    measurementId: 'G-GLY8N41RKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMu6QkvryxMcuJx5KA3QWa3YDS9-2Y4dw',
    appId: '1:178181282925:android:bb3cdc3c413a429984f364',
    messagingSenderId: '178181282925',
    projectId: 'fir-be1fc',
    storageBucket: 'fir-be1fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcBBNbPoLqtJRubQm7lErrA_iPgkOLRsw',
    appId: '1:178181282925:ios:2b4b7c310377b6a284f364',
    messagingSenderId: '178181282925',
    projectId: 'fir-be1fc',
    storageBucket: 'fir-be1fc.appspot.com',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcBBNbPoLqtJRubQm7lErrA_iPgkOLRsw',
    appId: '1:178181282925:ios:2b4b7c310377b6a284f364',
    messagingSenderId: '178181282925',
    projectId: 'fir-be1fc',
    storageBucket: 'fir-be1fc.appspot.com',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG2TmElFryA2lfd08zinarCQ-hfmnU_uU',
    appId: '1:178181282925:web:dad1b6b28456abe684f364',
    messagingSenderId: '178181282925',
    projectId: 'fir-be1fc',
    authDomain: 'fir-be1fc.firebaseapp.com',
    storageBucket: 'fir-be1fc.appspot.com',
    measurementId: 'G-WCKPV2XW71',
  );

}